### ISSUE TITLE
Running tests forever

### ISSUE THREAD

**Issue by panpanf** [wallabyjs/wallaby-polymer-sample#1]
OS: MAC OS X 10.10.4 
Node version: 5.4.0, NPM version: 3.3.12.

IDE: RubyMine 8.0.3

**Comment by ArtemGovorov** [comment]
Thanks!
Try adding `debug: true` to your config and paste the output from the Wallaby Console tab:

``` javascript
module.exports = function () {
  return {
    ...
    debug: true
  };
};
```

**Comment by ArtemGovorov** [comment]
Also try adding 

``` javascript
module.exports = function () {

  console.log(require('phantomjs2-ext').version);

  return { ...
```

to your config and share the version does it output in the Wallaby Console.

**Comment by panpanf** [comment]
2.1.1
Wed, 09 Mar 2016 05:25:33 GMT wallaby:project File cache: /Users/adobeinnovator/Library/Caches/RubyMine80/wallaby/projects/76e5ed5448dd591e
Wed, 09 Mar 2016 05:25:33 GMT wallaby:workers Parallelism for initial run: 6, for regular run: 3
Wed, 09 Mar 2016 05:25:33 GMT wallaby:workers Starting run worker instance #0
Wed, 09 Mar 2016 05:25:33 GMT wallaby:workers Starting run worker instance #1
Wed, 09 Mar 2016 05:25:33 GMT wallaby:workers Starting run worker instance #2
Wed, 09 Mar 2016 05:25:33 GMT wallaby:workers Starting run worker instance #3
Wed, 09 Mar 2016 05:25:33 GMT wallaby:workers Starting run worker instance #4
Wed, 09 Mar 2016 05:25:33 GMT wallaby:workers Starting run worker instance #5
Wed, 09 Mar 2016 05:25:33 GMT wallaby:workers Web server is listening at 50234
Wed, 09 Mar 2016 05:25:33 GMT wallaby:project Stopping process pool
Wed, 09 Mar 2016 05:25:33 GMT wallaby:project File cache is up-to-date, starting full test run
Wed, 09 Mar 2016 05:25:33 GMT wallaby:project Running postprocessor
Wed, 09 Mar 2016 05:25:33 GMT wallaby:postprocessor New TypeScript language service is required
Wed, 09 Mar 2016 05:25:33 GMT wallaby:postprocessor TypeScript postprocessor will be removed because in 4 project files none were found by patterns: *_/_.ts?(x)
Wed, 09 Mar 2016 05:25:33 GMT wallaby:project Postprocessor execution finished
Wed, 09 Mar 2016 05:25:33 GMT wallaby:project Postprocessor is removed as requested by itself
Wed, 09 Mar 2016 05:25:33 GMT wallaby:project Test run started; run priority: 3
Wed, 09 Mar 2016 05:25:33 GMT wallaby:project Running all tests
Wed, 09 Mar 2016 05:25:33 GMT wallaby:workers Starting test run, priority: 3
Wed, 09 Mar 2016 05:25:33 GMT wallaby:phantomRunner Starting sandbox [worker #0, session #jukla]
Wed, 09 Mar 2016 05:25:33 GMT wallaby:phantomRunner Preparing sandbox [worker #0, session #jukla]
Wed, 09 Mar 2016 05:25:33 GMT wallaby:browserRunner Total files to load in sandbox: 2
Wed, 09 Mar 2016 05:25:33 GMT wallaby:browserRunner Sandbox is generated [worker #0, session #jukla]: http://localhost:50234/wallaby_sandbox0.html
Wed, 09 Mar 2016 05:25:34 GMT wallaby:workers Started run worker instance (immediate) #5
Wed, 09 Mar 2016 05:25:34 GMT wallaby:workers Started run worker instance (immediate) #3
Wed, 09 Mar 2016 05:25:34 GMT wallaby:workers Started run worker instance (immediate) #4
Wed, 09 Mar 2016 05:25:34 GMT wallaby:workers Started run worker instance (immediate) #2
Wed, 09 Mar 2016 05:25:34 GMT wallaby:workers Started run worker instance (immediate) #0
Wed, 09 Mar 2016 05:25:34 GMT wallaby:phantomRunner Creating page for worker #0
Wed, 09 Mar 2016 05:25:34 GMT wallaby:workers Started run worker instance (immediate) #1
Wed, 09 Mar 2016 05:25:34 GMT wallaby:phantomRunner Phantom page created
Wed, 09 Mar 2016 05:25:34 GMT wallaby:phantomRunner Prepared sandbox [worker #0, session #jukla]
Wed, 09 Mar 2016 05:25:34 GMT wallaby:workers Running tests in sandbox [worker #0, session #jukla]
Wed, 09 Mar 2016 05:25:34 GMT wallaby:middleware Preparing to serve /Users/adobeinnovator/Library/Caches/RubyMine80/wallaby/wallaby/tracer.js
Wed, 09 Mar 2016 05:25:34 GMT wallaby:middleware Serving /Users/adobeinnovator/Library/Caches/RubyMine80/wallaby/wallaby/tracer.js from disk
Wed, 09 Mar 2016 05:25:34 GMT wallaby:middleware Preparing to serve /jasmine@2.3.4/framework.js
Wed, 09 Mar 2016 05:25:34 GMT wallaby:middleware Serving /jasmine@2.3.4/framework.js from disk
Wed, 09 Mar 2016 05:25:34 GMT wallaby:middleware Preparing to serve /jasmine@2.1.3/configurator.js
Wed, 09 Mar 2016 05:25:34 GMT wallaby:middleware Serving /jasmine@2.1.3/configurator.js from disk
Wed, 09 Mar 2016 05:25:34 GMT wallaby:middleware Preparing to serve /jasmine@2.1.3/reporter.js
Wed, 09 Mar 2016 05:25:34 GMT wallaby:middleware Serving /jasmine@2.1.3/reporter.js from disk
Wed, 09 Mar 2016 05:25:34 GMT wallaby:middleware Preparing to serve /test/simpleElementTest.js
Wed, 09 Mar 2016 05:25:34 GMT wallaby:middleware Serving /test/simpleElementTest.js from disk
Wed, 09 Mar 2016 05:25:34 GMT wallaby:middleware Preparing to serve /jasmine@2.1.3/starter.js
Wed, 09 Mar 2016 05:25:34 GMT wallaby:middleware Serving /jasmine@2.1.3/starter.js from disk

**Comment by ArtemGovorov** [comment]
Is there a `bower_components/webcomponentsjs/webcomponents-lite.js` file in the project?

**Comment by panpanf** [comment]
yes.

**Comment by ArtemGovorov** [comment]
If you comment out the `env` section completely:

```
    // env: {
    //   runner: require('phantomjs2-ext').path,
    //   params: { runner: '--web-security=false' },
    //   // Web components request JavaScript files so we need to clear page cache to avoid using the cached version
    //   clearMemoryCache: true
    // },
```

do you see any error in the Failing Tests tab?

**Comment by ArtemGovorov** [comment]
Also, could you please check if there is a `/Users/adobeinnovator/Library/Caches/RubyMine80/wallaby/projects/76e5ed5448dd591e/bower_components/webcomponentsjs/webcomponents-lite.js` file?

**Comment by ArtemGovorov** [comment]
From your console output, it looks like the `bower_components/webcomponentsjs/webcomponents-lite.js` is missing in wallaby cache, not sure why, because as you say it does exist in the project folder.

Try commenting out the `bootstrap` section completely and paste the Wallaby Console output with `debug: true`. Tests should fail, but at least the should finish running.

**Comment by panpanf** [comment]
No errors shown if comment out the env section.
Tests fail if comment out the bootstrap section.
no bower_components folder inside the /Users/adobeinnovator/Library/Caches/RubyMine80/wallaby/projects/76e5ed5448dd591e/ folder

**Comment by ArtemGovorov** [comment]
> no bower_components folder inside the /Users/adobeinnovator/Library/Caches/RubyMine80/wallaby/projects/76e5ed5448dd591e/ folder

Sorry, wrong folder, what about
`/Users/adobeinnovator/Library/Caches/RubyMine80/wallaby/projects/76e5ed5448dd591e/instrumented/bower_components/webcomponentsjs/webcomponents-lite.js`?

**Comment by panpanf** [comment]
No bower_components folder under /Users/adobeinnovator/Library/Caches/RubyMine80/wallaby/projects/76e5ed5448dd591e/instrumented

**Comment by ArtemGovorov** [comment]
Thanks, we are getting closer.
Try adding this to your wallaby config

``` javascript
module.exports = function () {

  console.log('WebComponents file:', require('fs').existsSync('bower_components/webcomponentsjs/webcomponents-lite.js'));
...
```

and paste the output from the Wallaby Console.

**Comment by panpanf** [comment]
output: WebComponents file: false

**Comment by ArtemGovorov** [comment]
It looks like that there's no `bower_components/webcomponentsjs/webcomponents-lite.js` file in your project, even though you've stated the opposite. Could you please double check it (including the case, spaces, etc)?

**Comment by panpanf** [comment]
Hey! I found the root cause. All libs are installed into app/bower_components on my machine. And it is because I have a .bowerrc file in the parent folder! Thanks for your help here. I will close this bug.
