### ISSUE TITLE
"ReferenceError: Can't find variable: Set"

### ISSUE THREAD

**Issue by edin0x** [wallabyjs/wallaby-polymer-sample#5]
When using the proposed configuration, I'm not able to get the tests running.
I get the following error:

```
ReferenceError: Can't find variable: Set
	at bower_components/webcomponentsjs/webcomponents-lite.js:129
```

Exact configuration I'm using:
```
module.exports = function() {
  return {
    files: [
      {pattern: 'bower_components/webcomponentsjs/webcomponents-lite.js', instrument: false},

      // Component and its files (files with load: false because they will be loaded by the component)
      {pattern: 'component/*', load: false},
    ],
    tests: ['src/**/*test.js'],

    env: {
      runner: require('phantomjs2-ext').path,
      params: {runner: '--web-security=false'},
      // Web components request JavaScript files so we need to clear page cache to avoid using the cached version
      clearMemoryCache: true,
    },

    // this allows wallaby to serve polymer files when requested by components
    middleware: function(app, express) {
      app.use('/polymer',
        express.static(
          require('path').join(__dirname, 'bower_components', 'polymer')));
    },

    // delaying running tests until web components are ready
    setup: function(wallaby) {
      if (!window.CustomElements || !window.CustomElements.readyTime) {
        wallaby.delayStart();
        window.addEventListener('WebComponentsReady', function() {
          wallaby.start();
        });
      }
    },
  };
};
```

Does anyone have an idea what I'm missing here?

**Comment by ArtemGovorov** [comment]
By default wallaby is using PhantomJs, that doesn't support ES6 Set. Try switching to [Chrome runner](https://wallabyjs.com/docs/integration/chrome.html).

**Comment by edin0x** [comment]
Thanks for the very fast reply! 

Setting the environment kind to 'chrome' seems to solve the issue. However, now I'm getting the following:
`Test run failure: Sandbox load failed, status: failed: Chrome is not running`

The Wallaby console gives me:
```
wallaby.js started
core v1.0.544
Error: connect ECONNREFUSED 127.0.0.1:56115
    at Object._errnoException (util.js:1026:11)
    at _exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1174:14)
```

**Comment by ArtemGovorov** [comment]
What is your local version of Chrome? Please also try the [Electron runner option](https://wallabyjs.com/docs/integration/electron.html).

**Comment by edin0x** [comment]
It seems the runner option that I left there was a problem. When I use electron I have an additional problem:

`Uncaught Error: Missing tracer start subscription at http://localhost:50112/__wallaby__/tracer.js:14`

Configuration:
```
module.exports = function() {
  return {
    files: [
      {pattern: 'bower_components/webcomponentsjs/webcomponents-lite.js', instrument: false},

      // Component and its files (files with load: false because they will be loaded by the component)
      {pattern: 'component/*', load: false},
    ],
    tests: ['src/**/*test.js'],

    env: {
      kind: 'electron',
    },

    // this allows wallaby to serve polymer files when requested by components
    middleware: function(app, express) {
      app.use('/polymer',
        express.static(
          require('path').join(__dirname, 'bower_components', 'polymer')));
    },

    // delaying running tests until web components are ready
    setup: function(wallaby) {
      if (!window.CustomElements || !window.CustomElements.readyTime) {
        wallaby.delayStart();
        window.addEventListener('WebComponentsReady', function() {
          wallaby.start();
        });
      }
    },
  };
};
```

**Comment by ArtemGovorov** [comment]
Looks like the `setup` code of the sample may be outdated, maybe the `WebComponentsReady` event is never triggered. We'll need to take a look and see what's changed since the last time the sample was updated.

**Comment by edin0x** [comment]
That could indeed be the case. I'm using Polymer 2.0 btw.

**Comment by ArtemGovorov** [comment]
Perhaps it makes sense to try finding out when Polymer 2 finishes the initialisation (so when to start running tests) and change the `setup` function accordingly. I suspect karma integration/config samples for Polymer 2 may have some code doing the similar thing.

**Comment by edin0x** [comment]
In any case, I can see that the `WebComponentsReady` event is triggered, so that should be fine.
According to documentation that should indeed indicate that the components are ready.
(https://github.com/webcomponents/webcomponentsjs#webcomponentsready)

**Comment by edin0x** [comment]
So it seems I had the path wrong where my components are located. Which brings me to the next step with the following error:

```
wallaby.js started
core v1.0.544
Failed to execute start operation, Error: Failed to parse src/types.js, SyntaxError: Unexpected token (4:7)
    at emitTwo (events.js:125:13)
    at process.emit (events.js:213:7)
    at emit (internal/child_process.js:774:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

Probably needs some more work on the configuration. Any ideas?

**Comment by ArtemGovorov** [comment]
How does your `src/types.js` looks like?

**Comment by edin0x** [comment]
Just a bunch of export types.

```
import * as Plottable from 'plottable';

// Browser
export type Credential = {|
  id: string,
  password: type
|};
...
```

Note also that when I restart Wallaby I randomly get other JS files which trigger the same error.

**Comment by edin0x** [comment]
Maybe it's worth noting we're using Flow for static type checking (https://flow.org/). I think this is causing these issues.

**Comment by ArtemGovorov** [comment]
Are you currently using Electron runner in your config? I don't think V8 version in Electron supports ES6 types yet. You may need to switch back to Chrome for that (if your version of Chrome supports ES6 modules). Otherwise you may use [Babel](https://wallabyjs.com/docs/integration/es-next.html) and [Webpack](https://wallabyjs.com/docs/integration/webpack.html) in your wallaby config (that you are probably using to build your app for production anyway).

Also, how do you currently run your tests outside wallaby (to make sure it is even possible to run them)?

**Comment by edin0x** [comment]
Yes I use the Electron runner and tried also with Chrome (v64..). 
Yes the tests run just fine when I run it through `jest`.

The project is indeed using Webpack and Babel. Let me try to figure out whether I get a working configuration with this additional processing first.

**Comment by ArtemGovorov** [comment]
> Yes the tests run just fine when I run it through `jest`.

Oh, then you don't need browser environment at all, neither you need this sample - it's all much simpler. Try this [docs section](https://wallabyjs.com/docs/integration/jest.html).

**Comment by edin0x** [comment]
That did the trick. The configuration is now a lot simpler. Thanks a lot for your help Artem!

Final configuration:
```
module.exports = function(wallaby) {
  return {
    files: [
      'src/**/*.js',
      '!src/**/*.test.js',
    ],
    tests: [
      'src/**/*.test.js',
    ],
    env: {
      type: 'node',
      runner: 'node',
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
    },

    testFramework: 'jest',

    debug: true,
  };
};
```

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
